/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package agenda;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kalema
 */
public class BusquedaTodas extends javax.swing.JInternalFrame {

    public DefaultTableModel modelo = new DefaultTableModel() {

        public boolean isCellEditable() {
            return false;
        }
    };

    /**
     * Creates new form BusquedaTodas
     */
    public BusquedaTodas() {
        initComponents();
        armarColumnas();
        //jtBusquedaKeyReleased();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRadioBotones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultado = new javax.swing.JTable();
        jbtCabiarEstado = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        jrPendientes = new javax.swing.JRadioButton();
        jrRealizada = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("BÚSQUEDA DE TODAS LAS TAREAS");
        jLabel1.setFocusable(false);

        jLabel2.setText("Ingrese el patrón de búsqueda");
        jLabel2.setFocusable(false);

        jtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtBusquedaKeyReleased(evt);
            }
        });

        jTResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTResultado);

        jbtCabiarEstado.setText("Cambiar Estado");

        jbtEliminar.setText("Eliminar");

        grupoRadioBotones.add(jrPendientes);
        jrPendientes.setText("Pendiente");

        grupoRadioBotones.add(jrRealizada);
        jrRealizada.setText("Realizada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jrPendientes)
                                        .addGap(45, 45, 45)
                                        .addComponent(jrRealizada))
                                    .addComponent(jtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 291, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtCabiarEstado)
                        .addGap(33, 33, 33)
                        .addComponent(jbtEliminar)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrPendientes)
                    .addComponent(jrRealizada))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtCabiarEstado)
                    .addComponent(jbtEliminar))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtBusquedaKeyReleased
        if (jrRealizada.isSelected()) {
            borrarFilas();
            for (Eventos listaEvento : Tareas.listaEventos) {
                if (jtBusqueda.getText().isEmpty()) {
                    borrarFilas();
                } else if (listaEvento.getEstado().equals("Realizado")) {
                    if (listaEvento.getNombre().startsWith(jtBusqueda.getText())) {
                        modelo.addRow(new Object[]{
                            listaEvento.getNombre(), listaEvento.getEstado(),
                            listaEvento.getFecha(), listaEvento.getLasCategorias()
                        });
                    }
                }
            }
        }
        if (jrPendientes.isSelected()) {
            borrarFilas();
            for (Eventos pend : Tareas.listaEventos) {
                if (jtBusqueda.getText().isEmpty()) {
                    borrarFilas();
                } else if (pend.getEstado().equals("Pendiente")) {
                    if (pend.getNombre().startsWith(jtBusqueda.getText())) {
                        modelo.addRow(new Object[]{
                            pend.getNombre(), pend.getEstado(),
                            pend.getFecha(), pend.getLasCategorias()
                        });
                    }

                }
            }
        }
    }//GEN-LAST:event_jtBusquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoRadioBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTResultado;
    private javax.swing.JButton jbtCabiarEstado;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JRadioButton jrPendientes;
    private javax.swing.JRadioButton jrRealizada;
    private javax.swing.JTextField jtBusqueda;
    // End of variables declaration//GEN-END:variables

    private void armarColumnas() {
        modelo.addColumn("Nombre Tarea");
        modelo.addColumn("Estado");
        modelo.addColumn("Fecha de inicio");
        modelo.addColumn("Categoria");
        jTResultado.setModel(modelo);
    }

    private void borrarFilas() {
        int filas = jTResultado.getRowCount() - 1;
        for (int i = filas; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    private void jtBusquedaKeyReleased() {
        if (jrRealizada.isSelected()) {
            //borrarFilas();
            for (Eventos listaEvento : Tareas.listaEventos) {
                if (jtBusqueda.getText().isEmpty()) {
                    borrarFilas();
                } else if (listaEvento.getNombre().startsWith(jtBusqueda.getText()) && listaEvento.getEstado().equals("Realizado")) {
                    modelo.addRow(new Object[]{
                        listaEvento.getNombre(), listaEvento.getEstado(),
                        listaEvento.getFecha(), listaEvento.getLasCategorias()
                    });
                }
            }
        }
        if (jrPendientes.isSelected()) {
            //borrarFilas();
            for (Eventos pend : Tareas.listaEventos) {
                if (jtBusqueda.getText().isEmpty()) {
                    borrarFilas();
                } else if (pend.getNombre().startsWith(jtBusqueda.getText()) && pend.getEstado().equals("Pendientes")) {
                    modelo.addRow(new Object[]{
                        pend.getNombre(), pend.getEstado(),
                        pend.getFecha(), pend.getLasCategorias()
                    });
                }
            }
        }
    }

}
